# =========================
# STAGE 1 - Build
# =========================
FROM maven:3.9.9-eclipse-temurin-21 AS builder

WORKDIR /build

# Copiamos pom primero (mejora cache)
COPY pom.xml .
RUN mvn -B -q dependency:go-offline

# Copiamos el código
COPY src ./src

# Build del jar
RUN mvn clean package -DskipTests


# =========================
# STAGE 2 - Runtime
# =========================
FROM eclipse-temurin:21-jre

WORKDIR /app

# Copiamos el jar generado
COPY --from=builder /build/target/*.jar /app/app.jar

EXPOSE 8080

ENTRYPOINT ["java","-jar","/app/app.jar"]

